### ISSUE TITLE
Building an application that uses Smart.Data.Accessor fails on Linux because of the WPF reference

### ISSUE THREAD

**Issue by masa-jnnjn** [usausa/Smart-Net-Data-Accessor#9]
Hi usausa,

 First of all, I would like to express my sincere appreciation to you for publishing such an excellent and helpful library. Thank you so much!

 I would like to build and run an ASP.NET Core application using Smart.Data.Accessor on Linux. However, I found that the building of my application fails on Linux.
  (I used .NET SDK 8.0.105 on Ubuntu Desktop 24.04 LTS) 

 The error that occurred was like as follows.

> You must install or update .NET to run this application.
> 
>   App: /home/******/.nuget/packages/usa.smart.data.accessor/2.5.6/tools/net8.0/Smart.Data.Accessor.Generator.Tools.dll
>   Architecture: x64
>   Framework: 'Microsoft.WindowsDesktop.App', version '8.0.0' (x64)
>   .NET location: /usr/lib/dotnet/
> 
>   No frameworks were found.

 And I found that Smart.Data.Accessor.Generator.Tools has the FrameworkReference to Microsoft.WindowsDesktop.App.WPF and it causes this issue. The FrameworkReference is written on the following line in the project file.
https://github.com/usausa/Smart-Net-Data-Accessor/blob/3e09cf7c077506097b01e981a16d9c1f5ad35252/Smart.Data.Accessor.Generator.Tools/Smart.Data.Accessor.Generator.Tools.csproj#L28

 Looking at the implementation, it seems that the Smart.Data.Accessor.Generator.Tools does not depend on WPF.

 As a trial, I created my own Usa.Smart.Data.Accessor NuGet package just deleting the above line from the project file and incorporated it into my application. Then, I could build and run it on Linux (and also on Windows) without any issues. The automatic generation of the Data Accessor implementations at build time also worked fine.

 I would be happy if this modification would be included as official.
 (Unless there are any other technical issues that I'm not aware of. For example, I have not been able to test how it would work with .NET6.)

 Thank you.

**Comment by usausa** [comment]
@masa-jnnjn
Thanks for using the library.
The reasons for the FrameworkReference to Microsoft.WindowsDesktop.App.WPF and the support for it are described below.

# Why FrameworkReference

The reason for the FrameworkReference is because of the following Issue.
https://github.com/dotnet/runtime/issues/37576

This library provides a mechanism for Smart.Data.Accessor.Generator.Tools(console application) to load the assemblies in a project post-build, analyse their metadata, generate source from metadata, and build additional assembly.
However, as in the Issue above, it is not possible to simply load ASP.NET Core or WFP assemblies from a console application.

If the console application has a FrameworkReference to Microsoft.AspNetCore.App/Microsoft.WindowsDesktop.App.WPF, ASP.NET Core and WFP assemblies can also be loaded.
For this reason, we have tentatively made it that way.

There is also a validation project on this subject here.
https://github.com/usausa/AssemblyLoadContextTest

# Current limitations

This library has the following limitations due to its structure.

- Smart.Data.Accessor.Generator.Tools does not work in environments where WPF cannot be built, as in this issue.
- Cannot support environments other than ASP.NET Core and WPF that require references to unknown FrameworkReference.

# Temporary measures

I would like to do the following.

- Include the following two Smart.Data.Accessor.Generator.Tools
  - Version with FrameworkReference for Windows environment
  - Version without FrameworkReference for non-Windows environment
- Use two different versions depending on build environment

# Complete measures

If I can figure out how to load ASP.NET Core or WFP assemblies from a console application without FrameworkReference, I would like to use that method.
Please let us know if you have any information on how to do this.

In addition, the current source generation is mechanically buggy in some respects.
We have been holding off on this because it would make metadata analysis more difficult, but in the future we would like to consider adopting a stable source generation mechanism using [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview).

**Comment by usausa** [comment]
@masa-jnnjn 
Try version 2.6.0.

**Comment by masa-jnnjn** [comment]
Thank you so much for your swift response. It worked perfectly!

Thanks also for the detailed explanation of why the FrameworkReference is set. 
(Very impressed and felt like I'd gazed into the dark abyss of .NET...)
